Name:           ros-kinetic-social-navigation-layers
Version:        0.3.1
Release:        1%{?dist}
Summary:        ROS social_navigation_layers package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/social_navigation_layers
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-costmap-2d
Requires:       ros-kinetic-dynamic-reconfigure
Requires:       ros-kinetic-people-msgs
Requires:       ros-kinetic-roscpp
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-costmap-2d
BuildRequires:  ros-kinetic-dynamic-reconfigure
BuildRequires:  ros-kinetic-people-msgs
BuildRequires:  ros-kinetic-roscpp

%description
Plugin-based layers for the navigation stack that implement various social
navigation contraints, like proxemic distance.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Tue Dec 06 2016 David V. Lu!! <davidvlu@gmail.com> - 0.3.1-1
- Autogenerated by Bloom

* Tue Dec 06 2016 David V. Lu!! <davidvlu@gmail.com> - 0.3.1-0
- Autogenerated by Bloom

